---
title: "R package tips"
author: "Tom Palmer"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 2
    code_download: true
    code_folding: show
    anchor_sections: true
---

```{r include=FALSE}
require("Hmisc")
```
`r Hmisc::hidingTOC(levels = 2)`

- Use `R CMD check`/`devtools::check()`/Check button in RStudio Build pane
  - Aim for 0 errors, 0 warnings - this is the minimum requirement for CRAN
  - can even setup a GitHub Action to run this on every commit into repo
    - `usethis::use_github_action()`/`usethis::use_tidy_github_actions()` or copy from https://github.com/r-lib/actions
  - Stata and python have no such similarly thorough checking system - so well worth using
- Define R package as an RStudio project (`.Rproj` file) to get the very helpful Build pane 
  - https://support.rstudio.com/hc/en-us/articles/200526207-Using-Projects
  - `BuildType: Package` (`None`/`Package`/`Makefile`/`Website`/`Custom`)
- Use classes for your functions (S3 easiest system; S4, RC)
  - Under S3 your class probably needs `print`, `summary`, `print.summary` methods, defined as e.g. `print.mynewclass <- function(){}`
- Use win-builder for a further check https://win-builder.r-project.org/
- Refer to https://r-pkgs.org/
- Use a visual git editor, e.g. GitHub desktop
  - Always work in a new branch (especially if working with others)
  - Make changes then work through changes - selecting relevant changed lines - giving sensible commit messages, i.e. not just one massive commit with message "Edits"!